const styles = {
    // Shared styles
    container: {
      display: 'flex',
      flexDirection: 'row',
      height: '100vh',
      width: '100vw',
      backgroundColor: '#ffffff',
    },
    navbar: {
      height: '60px',
      backgroundColor: '#ffffff',
      boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 1rem',
      position: 'sticky',
      top: 0,
      zIndex: 101,
      borderBottom: '1px solid #e5e7eb',
    },
    appName: {
      margin: 0,
      color: '#1e293b',
      fontWeight: '900',
      fontSize: '26px',
      cursor: 'pointer',
      transition: 'color 0.2s ease',
    },
    newChatButton: {
      backgroundColor: '#3b82f6',
      color: 'white',
      padding: '0.75rem 1rem',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      marginBottom: '1rem',
      fontSize: '14px',
      fontWeight: '500',
      transition: 'background-color 0.2s ease',
    },
    modelSelector: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      padding: '0.5rem 1rem',
      borderRadius: '20px',
      backgroundColor: '#f3f4f6',
      color: '#374151',
      cursor: 'pointer',
      fontSize: '14px',
      fontWeight: '500',
    },
    dropdownContent: {
      position: 'absolute',
      top: '35px',
      right: '0',
      backgroundColor: '#ffffff',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
      borderRadius: '8px',
      padding: '0.5rem',
      minWidth: '160px',
      zIndex: 102,
      border: '1px solid #e5e7eb',
    },
    dropdownItem: {
      padding: '0.5rem 1rem',
      cursor: 'pointer',
      color: '#1e293b',
      borderRadius: '4px',
      transition: 'background-color 0.2s ease',
      fontSize: '14px',
    },
  
    // HomePage-specific styles
    homeSidebar: {
      position: 'absolute',
      top: '60px',
      left: '0',
      width: '250px',
      height: '100%',
      backgroundColor: '#ffffff',
      color: '#1e293b',
      display: 'flex',
      flexDirection: 'column',
      padding: '1rem',
      boxShadow: '2px 0 10px rgba(0,0,0,0.05)',
      transition: 'left 0.3s ease',
      zIndex: 100,
      borderRight: '1px solid #e5e7eb',
    },
    chatHistoryItemContainer: {
      position: 'relative',
      overflow: 'hidden',
      marginBottom: '0.5rem',
      borderRadius: '6px',
    },
    chatHistoryItem: {
      backgroundColor: '#f1f5f9',
      padding: '0.75rem 1rem',
      borderRadius: '6px',
      cursor: 'pointer',
      fontSize: '14px',
      color: '#64748b',
      transition: 'transform 0.2s ease',
      position: 'relative',
      zIndex: 1,
    },
    deleteButton: {
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      width: '80px',
      backgroundColor: '#ef4444',
      color: 'white',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      zIndex: 0,
      transition: 'opacity 0.2s ease',
      opacity: 1,
    },
    chatContainer: {
      flex: 1,
      overflowY: 'auto',
      padding: '2rem 8rem 10rem',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      backgroundColor: '#f8fafc',
    },
    inputContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      padding: '1rem',
      backgroundColor: '#ffffff',
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      zIndex: 1000,
      width: '100%',
      margin: '0 auto',
    },
    queryBar: {
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: '#ffffff',
      borderRadius: '24px',
      border: '1px solid #e5e7eb',
      boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
      padding: '1rem',
      width: '100%',
      maxWidth: '900px',
      minHeight: '96px',
      gap: '0.75rem',
      position: 'relative',
      margin: '0 auto',
    },
    inputRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      width: '100%',
    },
    controlsRow: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      position: 'relative',
    },
    messageInput: {
      flex: 1,
      padding: '0.75rem 1rem',
      border: 'none',
      fontSize: '16px',
      backgroundColor: 'transparent',
      color: '#1e293b',
      outline: 'none',
    },
    actionButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '0.5rem',
      padding: '0.5rem 1rem',
      borderRadius: '20px',
      border: '1px solid #e5e7eb',
      backgroundColor: '#ffffff',
      color: '#4b5563',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      fontSize: '14px',
      fontWeight: '500',
      minWidth: '40px',
      height: '40px',
    },
    iconButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0.5rem',
      borderRadius: '20px',
      border: '1px solid #e5e7eb',
      backgroundColor: '#ffffff',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      width: '40px',
      height: '40px',
    },
    sendButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0.5rem',
      borderRadius: '20px',
      border: 'none',
      backgroundColor: '#3b82f6',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      width: '40px',
      height: '40px',
    },
    modelDropdownContent: {
      position: 'absolute',
      bottom: '100%',
      right: '0',
      backgroundColor: '#ffffff',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
      borderRadius: '8px',
      padding: '0.5rem',
      minWidth: '160px',
      zIndex: 103,
      border: '1px solid #e5e7eb',
    },
    userMessage: {
      backgroundColor: '#e9e9e980',
      padding: '1rem',
      borderRadius: '1.5rem',
      marginBottom: '1rem',
      fontWeight: '450',
      fontSize: '16px',
      maxWidth: '80%',
      alignSelf: 'flex-end',
      border: '2px solid #e9e9e980',
      color: 'black',
    },
    botMessage: {
      backgroundColor: '#ffffff',
      padding: '1rem',
      borderRadius: '1.5rem',
      marginBottom: '1rem',
      maxWidth: '80%',
      fontWeight: '450',
      fontSize: '16px',
      alignSelf: 'flex-start',
      border: '1px solid #e2e8f0',
      color: '#1e293b',
    },
    examplePrompt: {
      padding: '1.5rem',
      backgroundColor: '#ffffff',
      color: '#1e293b',
      borderRadius: '8px',
      marginBottom: '1.5rem',
      cursor: 'pointer',
      width: '100%',
      maxWidth: '600px',
      textAlign: 'center',
      fontSize: '16px',
      fontWeight: '500',
      transition: 'background-color 0.2s ease',
      border: '1px solid #e2e8f0',
      boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
  
    // ProfilePage-specific styles
    profileContainer: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center', // Center vertically
      padding: '2rem',
      width: '100%',
      maxWidth: '600px',
      margin: '0 auto', // Center horizontally
      minHeight: 'calc(100vh - 60px)', // Adjust for navbar height
    },
    profilePictureContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      marginBottom: '2rem',
    },
    profilePicture: {
      width: '120px',
      height: '120px',
      borderRadius: '50%',
      backgroundColor: '#e2e8f0',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: '1rem',
      objectFit: 'cover',
    },
    uploadButton: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      padding: '0.5rem 1rem',
      borderRadius: '20px',
      border: '1px solid #e5e7eb',
      backgroundColor: '#ffffff',
      color: '#4b5563',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      fontSize: '14px',
      fontWeight: '500',
    },
    inputContainerProfile: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      gap: '1rem',
      marginBottom: '2rem',
    },
    input: {
      padding: '0.75rem 1rem',
      border: '1px solid #e5e7eb',
      borderRadius: '8px',
      fontSize: '16px',
      backgroundColor: '#ffffff',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
    },
    disabledInput: {
      padding: '0.75rem 1rem',
      border: '1px solid #e5e7eb',
      borderRadius: '8px',
      fontSize: '16px',
      backgroundColor: '#f3f4f6',
      color: '#6b7280',
      outline: 'none',
      width: '100%',
    },
    updateButton: {
      backgroundColor: '#3b82f6',
      color: 'white',
      padding: '0.75rem 1.5rem',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      fontSize: '16px',
      fontWeight: '500',
      transition: 'background-color 0.2s ease',
    },
    backButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0.5rem',
      borderRadius: '20px',
      border: '1px solid #e5e7eb',
      backgroundColor: '#ffffff',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
      width: '40px',
      height: '40px',
    },
  };
  
  export default styles;